### ISSUE TITLE
Idea: Use the tool to generate stubs

### ISSUE THREAD

**Issue by Sytten** [chadrik/doc484#1]
I followed the multiple PRs you did some years ago to get this tool to be integrated in mypy and I finally landed on this jewel. I want to go a step further and use your tool to generate stubs that could be submitted to typeshed. I feel this could be very valuable for the community to avoid writing manual stubs. Could you point me to some key parts that would need to be adapted to do that? 
Thanks!

**Comment by chadrik** [comment]
Hi, so funny enough I went looking for some info on mypy's `stubgen` tool to point you in that direction, but it looks like `stubgen` now supports parsing info from docstrings, so you don't even need this project.  If you run into issues, you'll want to modify the [mypy/stubdoc.py](https://github.com/python/mypy/blob/master/mypy/stubdoc.py) file and submit a PR for it.  Best of luck!

**Comment by daniele-niero** [comment]
But it only support rst (sphinx) docstrings, while your project support them but also numpy and google docstring style, as it should be. 
Rst is powerful, but way to verbose for function/classes docstrings

**Comment by chadrik** [comment]
I think the easiest solution would be to run doc484 on your code to generate comments, then use mypy's `stubgen` to make the stubs.
